### ISSUE TITLE
Refactor Bad Browser Check

### ISSUE THREAD

**Issue by skubakdj** [MyCryptoHQ/MyCrypto#1084]
There are several changes we can make to our bad browser check that will allow us to harden app-wide security: 

 1. Move the check out of `index.html` to its own individual file. This will allow us to restrict the execution of inline JavaScript.
 2. Remove calls to `eval`. Allows us to restrict the page from having access to `eval` entirely.

**Comment by wbobeirne** [comment]
This definitely wasn't my ideal solution for the bad browser check, but I'll definitely say this is a tricky one to fulfill all of the requirements of and have it still work for a few issues:

* The JS is in index.html because it can't be a part of the main bundle. Any language feature used that the user's browser doesn't handle results in the bundle not loading, and a white screen.
* `eval` is the only bullet-proof way to check for certain language features, like `let` and `const`. Anything else is a heuristic, not an actual check.
* I don't think you can outright disable eval in a traditional browser? But I belive this is possible on Electron, though that's already sandbox'd and only runs local JS as-is.

There are a few possible ways to get around these issues

* Make the bad browser checker its own Webpack bundle. This would separate it from errors of the other bundles, but also means that if any of the generated Webpack code isn't kosher, then it still fails. Pretty unlikely though.
* Make the bad browser check a thing to be _not_ triggered, rather than actively triggered. We could possibly check to see if the page hasn't loaded X seconds after all assets have been downloaded, and if so, let the user know something went wrong. This could result in some false positives though.

Anyway, just some thoughts on the problem. It's a doozy.
