### ISSUE TITLE
Private Key input field bug

### ISSUE THREAD

**Issue by hahnmichaelf** [MyCryptoHQ/MyCrypto#1090]
If you try to access your wallet via private key, you normally have this box:

![normal1](https://user-images.githubusercontent.com/29407814/36183463-6197b866-10fc-11e8-88c0-46e0d428717a.PNG)

However, if you enter 128 characters into the private key field, you have a password field pop up.

![abnormal2](https://user-images.githubusercontent.com/29407814/36183588-e156d762-10fc-11e8-8f9b-bdf20b2a4b51.PNG)

This also occurs with 132 characters.

![abnormal1](https://user-images.githubusercontent.com/29407814/36183602-ed6292bc-10fc-11e8-92fe-607b6943eae7.PNG)

Is this intended functionality?

**Comment by wbobeirne** [comment]
Yep, fully intentional. In the [component](https://github.com/MyCryptoHQ/MyCrypto/blob/develop/common/components/WalletDecrypt/components/PrivateKey.tsx#L37), there's a check using [this util function](https://github.com/MyCryptoHQ/MyCrypto/blob/develop/common/libs/validators.ts#L97) to check if it's an encoded private key. I think this was some kind of precursor to keystore files, but honestly I don't have all of the history behind it.
