### ISSUE TITLE
Self send prompts when not supposed to 

### ISSUE THREAD

**Issue by james-prado** [MyCryptoHQ/MyCrypto#1103]
Steps to reproduce:
- Log into keystore file,
- Change wallets,
- Send transaction to keystore address

<img width="1552" alt="screen shot 2018-02-15 at 6 49 04 pm" src="https://user-images.githubusercontent.com/13836920/36290113-ed56f6fc-1280-11e8-8ab7-cbdb6609c97e.png">

**Comment by wbobeirne** [comment]
Looks like this is a sticky state problem: The component grabs the address when it mounts, and never gets unmounted, even when you go to unlock a new wallet. I'll definitely fix this up for this component, but it may be wise to unmount rather than hide all of these components during wallet selection, to reduce the chances of this cropping up elsewhere.

Nice catch!
