### ISSUE TITLE
Sign/Verify Message Bug & Improvements

### ISSUE THREAD

**Issue by MysticRyuujin** [MyCryptoHQ/MyCrypto#1136]
There are three things that bother me about the Sign Message feature:

The first I see as a bug:

1. It's in the footer with a static URL to `https://www.mycrypto.com/signmsg.html` this prevents users who download MyCrypto and run it locally from running that feature locally. However, the `signmsg.html` is part of the local download copy so there's no reason to not use a relative URL?

The second is an oddity but I don't think it actually matters:

2. When you load the page it appears to always connect to `mycryptoapi.com` even if you previously had another node selected. I don't think being connected to a node matters at all for this function/feature so perhaps this is a non-issue.

The 3rd I see more as a feature request 😄 

3. The "Verify Message" function is just a big text box that requires a pre-formatted JSON. I think it would be cool to have a field input option similar to `https://etherscan.io/verifySig` to make it a little more user friendly.

**Comment by wbobeirne** [comment]
Hey @MysticRyuujin, as far as I can tell these are all issues that are about the version of MyCrypto that's currently in production. You can find the issue queue for that over at https://github.com/MyCryptoHQ/mycrypto.com, this is for the not-yet-released beta version. I think you'll find problems 1 and 2 aren't an issue in the beta.

As for 3, while I think their UI is nicer, I think the UX of having one thing to paste in is a good deal more convenient than having to paste in a bunch of stuff. But I also agree that our verify is a little... lackluster at the moment.

I'm going to close this issue since most of it is in reference to the production site, but if you want to make a new issue about sprucing up verify, go ahead. Thanks for posting!
