### ISSUE TITLE
Fix typings for stored Big Numbers

### ISSUE THREAD

**Issue by aitrean** [MyCryptoHQ/MyCrypto#1198]
In #608, I'm creating new Bignumber instances out of the Bignumber-typed values we pass through the selectors (see transaction.ts). This solution is quick, but not ideal. We're currently defining properties such as gasLimit.value as BN. However, they do not have any of the actual BN functions attached to them, so calls like gasLimit.value.mul(a) will not be recognized. I'm looking to change the reducers and selectors to store big numbers as strings, and convert them back to actual BN objects passed through the selectors.

**Comment by wbobeirne** [comment]
I've not experienced this issue, is it possible that this only happens when BNs are restored from local storage serialization? Pretty much all of our balances are BNs that are stored in Redux, and fetched by selectors.

**Comment by HenryNguyen5** [comment]
All of the balances should be BNs, I haven't run into this issue either. Do you have a repro case I could look at? Before the transaction stack refactor we would store the balances as strings but that comes with a slew of problems ( is it in base 10? 16? if it is in base 16 does it have a 0x prefix or not? This could be solved by using opaque types, but would require a large refactor of its own currently.) which is why all balances are now stored as BNs in the reducer. Also, if any selector encounters high load, you'll be adding a lot of additional overhead re-instantiating balances as BNs

**Comment by aitrean** [comment]
During testing, I was inserting the JSON state for a store into the selectors. However, when trying to test selectors that relied on BN methods (see getValidGasCost(), getGasCost() under selectors/transaction), Typescript would complain that the methods did not exist. Since the store is all serialized, we aren't keeping actual BN function data stored there. In which case, I'm confused as to how we're treating the selector BN values as full BN objects with call-able methods, or why they work in production but not when I pass in the raw json store?

**Comment by wbobeirne** [comment]
BN can't be serialized into JSON, so depending on your methodology of testing, it won't actually be a BN that's getting put in. If you try to go from a snapshot to a selector, that also won't likely work since the snapshots just serialize everything.

When you say tests, do you mean unit tests, or was it something more ad-hoc?

**Comment by wbobeirne** [comment]
^ Continuing the conversation in the PR, and closing this issue since I think this is a testing methodology issue, and not something wrong with how we store state.
