### ISSUE TITLE
Swap Timer Freezes on Tab Change

### ISSUE THREAD

**Issue by dternyak** [MyCryptoHQ/MyCrypto#1241]
Steps to reproduce:

1. Create any swap
2. Change tabs (not windows)
3. Return back to swap
4. Notice that timer is frozen when you left

**Comment by MrLuit** [comment]
Cannot reproduce on Windows 10 using Chrome / Firefox / Edge

**Comment by dternyak** [comment]
Interesting. On Mac I can reproduce reliably: 

![2018-03-04 14 11 41](https://user-images.githubusercontent.com/7861465/36950039-feeb85a8-1fb5-11e8-8a86-3324d3a41b99.gif)

**Comment by wbobeirne** [comment]
I think the root of this problem is the swap timer is currently stored in Redux as `secondsRemaining`. I think this organization is really bad, because it requires redux state to be updated every second to decrement the timer, and requires a saga or something to know when to start / stop countdown.

This should ideally be stored as a timestamp, and we should do the second countdown in state for timer component.
