### ISSUE TITLE
SCAN for coins on a Trezor

### ISSUE THREAD

**Issue by CryptoToit** [MyCryptoHQ/MyCrypto#1270]
After login with a TREZOR > View Account > Scan for Tokens

Found:
SNM
ZRX

However I have the following on my Trezor:
AST
BPT
ENJ
KNC
NULS
SNM
UTK
ZRX
cV

When I try for the second time (after logging in again) I get the following error msg: 

Token Balances
Failed to fetch token values

**Comment by wbobeirne** [comment]
The majority of your missing tokens simply aren't on our list of tokens over here: https://github.com/MyCryptoHQ/MyCrypto/blob/develop/common/config/tokens/eth.json. We're currently working on expanding that.

As for the second failed load, would you be able to open up your Javascript console and copy / paste whatever error is in there? There are many reasons that a load might fail.

**Comment by CryptoToit** [comment]
Once Wallet is open and it displays the coins (the 2 it picks up form the original post) and I then do a "scan for new tokens":

"Failed to fetch token values"

client.1be3dddc.js:11 Failed to scan for tokens Error: unsupported value conversion
    at handleValues (client.1be3dddc.js:1)
    at TokenValue (client.1be3dddc.js:1)
    at response.map.item (client.1be3dddc.js:1)
    at Array.map (<anonymous>)
    at client.batch.then.response (client.1be3dddc.js:1)
    at <anonymous>
scanWalletForTokens @ client.1be3dddc.js:11

**Comment by wbobeirne** [comment]
Thanks, that's extremely helpful and narrows down where this is happening to https://github.com/MyCryptoHQ/MyCrypto/blob/develop/common/components/BalanceSidebar/EquivalentValues.tsx#L261

The presence of custom tokens definitely seems like it could be related. Would you mind sending me the following information in an email (for your privacy):
* Your ETH address (_NOT_ your private key)
* The two custom tokens info:
  * Symbol
  * Contract address
  * Decimal

You can email me at will(at)mycrypto.com. That should be enough info to replicate the issue so that we can solve it. Thanks!

**Comment by wbobeirne** [comment]
My previous comment was wrong, it's actually happening here: https://github.com/MyCryptoHQ/MyCrypto/blob/develop/common/libs/nodes/rpc/index.ts#L80 It looks like this happens when the balance checks error out. Here's an example of one of them erroring:

#### Request
```
{
  "method": "eth_call",
  "params": [
    {
      "to": "0x983f6d60db79ea8ca4eb9968c6aff8cfa04b3c63",
      "data": "0x70a0823100000000000000000000000030cf8aa72c4e69e35e0e48e785176704d6d70c7d"
    },
    "pending"
  ],
  "id": "ccd3f8a83671b8c23dc33a7085eaf5e3",
  "jsonrpc": "2.0"
}
```
#### Response
```
{
  "jsonrpc": "2.0",
  "error": {
    "code": -32015,
    "message": "Transaction execution error.",
    "data": "Internal(\"Database missing expected key: e1b9…75a7\")"
  },
  "id": "ccd3f8a83671b8c23dc33a7085eaf5e3"
}
```

It looks like whatever we're doing to verify the balances are OK isn't working quite right. This ends up going to the success case, where it errors out because response.result is `undefined`.

**Comment by wbobeirne** [comment]
Closing this in favor of the more focused #1293.
