### ISSUE TITLE
Cannot Make Transaction with 0 ETH

### ISSUE THREAD

**Issue by ChosunOne** [MyCryptoHQ/MyCrypto#1275]
### Description of the Issue

When attempting to make a transaction with 0 ETH being sent, the interface prevents me from signing the transaction, regardless of the presence of data in the transaction.

### Steps to Reproduce

Unlock a wallet with a Ledger, then attempt to make a self transaction with 0 ETH in the amount.  

### Description of Your Machine

Google Chrome Version 64.0.3282.186 (Official Build) (64-bit)
Windows 10

### Console Logs / Screenshots

[Screenshot of the issue](https://imgur.com/a/aiKOB)

**Comment by wbobeirne** [comment]
Thanks for the report, I think we completely overlooked this (obvious, now seeing it) use case. I've marked this as high priority since it blocks a pretty normal use case.

In the mean time, a workaround could be to send an extremely small amount (1 wei) so long as that doesn't affect your contract in an undesirable way.

Thanks for the report!

**Comment by ChosunOne** [comment]
Thanks for the response.  I also sometimes like to send 0 ETH to confirm I've typed in an address correctly without risking any of my funds.
