### ISSUE TITLE
ShapeShift Box UI

### ISSUE THREAD

**Issue by dternyak** [MyCryptoHQ/MyCrypto#1277]
"Revert to the previous Shapeshift UI to see everything in one box."

https://medium.com/@RaymondDurk/mycrypto-beta-is-a-great-sign-for-things-to-come-6e1f756b28d2

Beta ShapeShift Coin/Token dropdown should show all supported coins similar to production:
<img width="829" alt="screen shot 2018-03-12 at 12 28 59 am" src="https://user-images.githubusercontent.com/7861465/37267137-606183ce-258c-11e8-8ec1-f59b1d83e9a8.png">

ShapeShift's marketing videos show the usage of this UI, and user feedback has been that it is easier to navigate coin selection with the older UI.

Showing token symbols after a token has been selected, like below, is a great addition and should be maintained. <img width="133" alt="screen shot 2018-03-12 at 12 30 41 am" src="https://user-images.githubusercontent.com/7861465/37267184-9c2b19f6-258c-11e8-940a-7a64aff95058.png">

**Comment by wbobeirne** [comment]
Yeah, I'm also game for moving back to this. As a thought though, do you think we should maybe move more common currencies to a more prominent view? I'm thinking ETH and Bitcoin could possibly larger up top, I always end up having to hunt down ETH at least since that's what I most commonly use. Just a thought.

**Comment by dternyak** [comment]
Experimentation sounds great to me! 

I agree there are more common pairs that we can better emphasize.
