### ISSUE TITLE
Update Translations

### ISSUE THREAD

**Issue by james-prado** [MyCryptoHQ/MyCrypto#1285]
With the release of the beta, we've added and update a lot of copy throughout the site. To provide translations, all the new 'raw' text needs to be added to the translation files.

**Comment by wbobeirne** [comment]
Likewise, this would be a good opportunity to clear out unused translations. I'd like to see the following things done as a part of this cleanup, please comment if you think any of these are out of scope:

1. Wrap all user-facing copy in `translate` and `translateRaw` calls
2. Identify as many common use string as possible, and re-key those as `x_NameOfString`. Some of our common use strings are in really weird keys, like `"OFFLINE_Step2_Label_3": "Gas Price"`. This should just be `x_GasPrice`.
3. Create a way to pass variables to translations. Right now the way we do untranslated dynamic copy is usually something like `You are about to send ${amount}  to ${address}`, and for translated stuff, we usually just tack it on to the end. What would work 100x better for localization is if we allow tokens that get replaced in translations. For instance, something like `You’re sending $amount to $address" so that other languages that have different grammar can re-arrange those tokens as needed. It could be called like
  ```
  translate('SEND_summary', {
    amount: tx.amount,
    address: tx.to
  });
  ```
4. Allow for some kind of configurable way to highlight translated copy. This should help with visual auditing to make sure everything is wrapped. This probably doesn't need to be fancy, it could just be a dev-only query param.

**Comment by james-prado** [comment]
Those are all good suggestions. All the translations will be cleaned up, renamed (for those that need it), old strings removed. Adding tokens to translation strings is a great idea, I'll update the translate functions and any existing strings to use string literals for variables like amounts or addresses

I'm not sure if there's anyway I can properly highlight every translated string. If we were using just `translate` everywhere, a class could be appended onto the parent text's parent `<span />`, but then we'd have a bunch of extra `<span />`'s everywhere

**Comment by wbobeirne** [comment]
We could choose to only wrap with spans when translation is enabled. For translateRaw, we could probably add some kind of unique character to the translated text to show it's been translated, like everyone's favorite unicode snowman `☃`

That could totally be a future PR though.

**Comment by james-prado** [comment]
naw, I think it would be helpful to do it in this pr. I'll probably just use emoji's though, more fun. Something like 🎉
