### ISSUE TITLE
Metamask should be enabled for other networks

### ISSUE THREAD

**Issue by rstormsf** [MyCryptoHQ/MyCrypto#1363]
https://github.com/MyCryptoHQ/MyCrypto/blob/develop/common/selectors/config/wallet.ts#L68

This is not true. Metamask works fine with any other network by using Custom RPC option.
I don't think you should only let those `whitelisted` networks to only work with MyCrypto...

**Comment by wbobeirne** [comment]
You're totally right, but I actually think enabling / disabling MetaMask needs even more overhauling. Basically, we just use the network MetaMask is configured with at the time of connecting. It doesn't actually respect the dropdown in the top right, it just uses whatever you've configured in the MetaMask chrome extension. So we should probably do one of two things:

1. Just enable Web3 all the time, since it's going to change to the right network anyway, or
2. Disable Web3 unless its network matches the one that you're currently connected to on MyCrypto. We can check `window.web3.version.network` against the network chain id.

I think 1 is the best solution for ease of use, but it's important that we communicate to users when they switch networks.

**Comment by dternyak** [comment]
@wbobeirne How do you think we can best communicate that the user has switched networks when they unlock metamask with different network selected in the dropdown? Perhaps a simple `showNotification` message?
