### ISSUE TITLE
Textarea UI Quirks

### ISSUE THREAD

**Issue by dternyak** [MyCryptoHQ/MyCrypto#1392]
Re-styled elements which were previously textareas no longer have multiple rows of spacing by default,

![screen shot 2018-03-26 at 7 12 42 pm](https://user-images.githubusercontent.com/7861465/37939759-43b4e64a-312a-11e8-8535-3a4897751250.png)
![screen shot 2018-03-26 at 7 13 39 pm](https://user-images.githubusercontent.com/7861465/37939760-43c8dc54-312a-11e8-9db9-5b05e6d10a2a.png)

These are likely originating from a similar styling issue, perhaps from https://github.com/MyCryptoHQ/MyCrypto/pull/1333 (@james-prado can help determine if this is indeed the cause)

**Comment by james-prado** [comment]
Yes #1333 is the cause.

In the first image the placeholder text is longer than the textarea. Increasing the height of the textarea will fix this. Also since it's a textarea input, it should by default be ~3-4 rows in height.

In the second image the signed transaction was intentionally made into an input, I don't think it's really necessary to have a textarea for a long hexencoded string that's only ever copy pasted. The placeholder text should be truncated though.

**Comment by wbobeirne** [comment]
Add the View Address decrypt to this list as well:

<img width="1033" alt="screen shot 2018-03-27 at 7 56 56 am" src="https://user-images.githubusercontent.com/649992/37965831-7292fb90-3194-11e8-906b-0176bf8f3a6c.png">

It should probably just be an input.
