### ISSUE TITLE
Mnemonic Modal Translation Bug

### ISSUE THREAD

**Issue by dternyak** [MyCryptoHQ/MyCrypto#1433]
<img width="857" alt="screen shot 2018-04-03 at 2 51 21 pm" src="https://user-images.githubusercontent.com/7861465/38272341-8e7c7d4e-374e-11e8-8257-cf4f8c4ea196.png">

**Comment by wbobeirne** [comment]
Also noticed this on custom node modal

**Comment by jonathandiep** [comment]
Looking at `MyCrypto/common/components/WalletDecrypt/components/Mnemonic.tsx` and there is a  `'MNEMONIC'` string that is passed down as `walletType` props to `<DeterministicWalletsModal>`. 

The modal then tries to translate `DECRYPT_PROMPT_UNLOCK_${walletType}`. However, the translation file doesn't have `DECRYPT_PROMPT_UNLOCK_MNEMONIC` so that's the text that gets displayed. Seems like this can be solved by creating `DECRYPT_PROMPT_UNLOCK_MNEMONIC` in the translation files or by using `LEDGER` or `TREZOR` as the `walletType`.

The custom node modal is a simple fix. Just needs to change `Node_Title` to `NODE_TITLE` in `MyCrypto/common/components/Header/components/CustomNodeModal.tsx` 🙂

**Comment by wbobeirne** [comment]
One more

<img width="400" alt="screen shot 2018-04-11 at 1 10 23 pm" src="https://user-images.githubusercontent.com/649992/38632138-c315c42a-3d89-11e8-9a9d-3638f084a8c4.png">

**Comment by jonathandiep** [comment]
So I'm actually able to fix the issues above and would like to make my first PR. But I have no idea what the title for the mnemonic modal should be. Any suggestions?

![screen shot 2018-04-11 at 11 26 38 pm](https://user-images.githubusercontent.com/8920301/38659886-356dea06-3de0-11e8-8a0a-c7be8f2b4641.png)

**Comment by wbobeirne** [comment]
@jonathandiep thanks for pitching in, I ended up snapping these issues up and a couple more as a part of #1506.
