### ISSUE TITLE
[Coin Req] Add MUSIC to MyCrypto

### ISSUE THREAD

**Issue by Varunram** [MyCryptoHQ/MyCrypto#1474]
Musicoin recently had a hardfork which enables EIP 155 and that should ideally make it work with MyCrypto (ref. https://github.com/kvhnuke/etherwallet/issues/912 ) I can PR back with the code if the devs are okay with adding Musicoin back, so do let me know reg this. Thanks!

**Comment by wbobeirne** [comment]
Hey @Varunram, thanks for the heads up. We definitely can get MUSIC back in. Our network and node configs are a little bit of a pain to configure right now due to some recent features, so I'd be happy to fill out that PR for you. All I need is the following information about MUSIC:

* What is the new chain ID?
* What is the preferred block explorer for linking to addresses / transactions / blocks?
* What BIP44 derivation paths are used for MUSIC wallets?
* What are the ideal gas settings (minimum, maximum, default?)
* What is a reliable public node we can use?

Thanks!

**Comment by frankurcrazy** [comment]
Hi @wbobeirne:

Allow me to fill the information about MUSIC:
**Chain ID:** 7762959
**Block explorer:** 
 - name: 'Musicoin Explorer'
 - origin: 'https://explorer.musicoin.org'
**BIP44 Path:** m/44'/184'/0'/0
**Gas settings:** 
 - min: 1
 - max: 60
 - initial: 20
**Public node:** https://mewapi.musicoin.tw

Thanks

**Comment by Varunram** [comment]
Thanks @frankurcrazy! @wbobeirne, I can confirm that the provided information is correct. Another public node instance that we (at the Musicoin Foundation host is `167.114.185.191`. Thanks!

**Comment by wbobeirne** [comment]
@Varunram @frankurcrazy I've opened a PR (#1532) that adds this. Would you two mind confirming that it all looks good? You can use https://mycryptobuilds.com/1f7bde31532556ef27497933ca3797f765cefb52/ to quickly try it out. Most importantly, would you mind confirming if mnemonics work as expected? I'm finding that my phrase generates a different address than the Music Wallet app.

**Comment by Varunram** [comment]
@wbobeirne Nice catch! I just double checked with the wallet and we use `m/44'/60'/0'/0`, so Frank was not right in that context. Thanks!
