### ISSUE TITLE
Parity Signer modal doesn't pop up for contract txs

### ISSUE THREAD

**Issue by maciejhirsz** [MyCryptoHQ/MyCrypto#1481]
### Description of the Issue

If you try to interact with a contract, the QR code modal doesn't pop up since it's only nested in the transfer component.

### Steps to Reproduce

Attempt to send a transaction by doing a call to a contract, choose Parity Signer to sign the tx.

I can attempt to fix when I have some time unless you guys beat me to it.

**Comment by wbobeirne** [comment]
This is my mistake, I had recommended moving the component out of the top layer and into the send view specifically. But after the redux changes to it, it makes more sense for it to be top level (Since anything could trigger the sign qr action.)

I think the fix should be as simple as moving it up to the top of the render tree.

**Comment by maciejhirsz** [comment]
Not necessarily part of this issues, but would it be possible to have a universal modal popup action (since you never really have more than one)?

For example the action object could be be:

```js
{
  action: 'OPEN_MODAL',
  payload: {
    Component: SomeModalComponent,
    props: { /* props to init the modal with */ }
  }
}
```

**Comment by wbobeirne** [comment]
Yeah, that would make a ton of sense as a refactor. I went ahead and solved this one as-is for now though.
