### ISSUE TITLE
Connection Issue

### ISSUE THREAD

**Issue by CryptoToit** [MyCryptoHQ/MyCrypto#1658]
When I use scan for Tokens I keep getting a "connection lost" error. I have no connection issues, and this is happend on every occasion over 2 days of trying to use.

![screen shot 2018-04-22 at 13 38 24](https://user-images.githubusercontent.com/36384396/39094620-9cbaee48-4632-11e8-8c24-16e6f1f6bece.png)

**Comment by wbobeirne** [comment]
This looks like the result of a request failing due to an error, and our code thinking that the node is offline because it's not returning what we expected. Can you provide more information about which tokens you expected to come up, and which network you have selected in the top right? If you're willing to share your address, but don't want to do so publicly, feel free to hop on our public Discord or shoot me an email (will [at] mycrypto.com) with that information.

Thanks for reporting!
