### ISSUE TITLE
[ALL beta+main] Cannot add custom network

### ISSUE THREAD

**Issue by rstormsf** [MyCryptoHQ/MyCrypto#1807]
Affected: 
https://mycrypto.com 
https://beta.mycrypto.com 

1. Add custom Node
2. Specify URL https://sokol.poa.network
3. Select `Custom` for Network dropdown
4. Specify Chain ID: 77
5. Specify Currency Name: SPOA
6. set some custom network name: Sokol testnet
7. Press `Save & Use Custom Node`

Receive JS error:

![image](https://user-images.githubusercontent.com/9360827/40082065-ba53f124-5844-11e8-8b03-170a610ce3c6.png)

this error prevents me from interacting with smart contracts, it doesn't allow me to specify contract address in the Contract tab. Critical bug IMHO hence making MyCrypto completely unusable on custom chains

**Comment by wbobeirne** [comment]
In case someone else tackles this, it's in the `getDecimalFromUnit` function in `selectors/transaction/meta.ts`

**Comment by ConnorBryan** [comment]
@wbobeirne I think the actual issue here might be that this particular usecase was invoking a circular dependency issue. Because the results from the selector return `undefined` in `master`, but not so in `develop` (where all circular dependencies were fixed), I believe this to be the case. Thoughts?

Circular dependencies in master:
<img width="660" alt="screen shot 2018-06-21 at 5 27 55 pm" src="https://user-images.githubusercontent.com/10479826/41748673-7684c9d6-7578-11e8-8898-4e1a3c3c8b87.png">

**Comment by ConnorBryan** [comment]
I got with @dternyak and @HenryNguyen5 to make sure this was fixed, and was instructed to comment out a static network/node and re-add it. 

I was able to do so without any errors, and I was also able to do so with `SPOA` defined above, so I'm closing this as fixed pending further problems.
