### ISSUE TITLE
Open Etherscan address page with Trezor or Ledger Wallet

### ISSUE THREAD

**Issue by wchuan11** [MyCryptoHQ/MyCrypto#1825]
### Description of the Issue

In new Mycrypto, it is no longer able to click on the ETH balance and open the new tab to Etherscan address page.

### Steps to Reproduce

Connect to Ledger/Trezor wallet, the window wallet will popup. In legacy Mycrypto, the ETH balance of each address is clickable and will open the Etherscan address page on a new tab.

### Screenshots

[New Mycrypto]
![capture41](https://user-images.githubusercontent.com/467814/40279560-32075518-5c77-11e8-9db6-3e4fcfb6ffec.PNG)

[Legacy Mycrypto]
![capture41-2](https://user-images.githubusercontent.com/467814/40279566-4fe73d64-5c77-11e8-93e2-d0212ade195a.PNG)

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/776566136827883)

**Comment by wtzb** [comment]
Thank you for opening this issue. Since this issue applies to an older, no longer supported version of MyCrypto, I'm closing this to keep a better overview of issues that are currently applicable.

If you believe this was in error, or if this issue still applies, please don't hesitate to comment or [reach out to us directly](https://support.mycrypto.com/contact-us). Thanks for helping us and letting us know of any issues you might run into!
