### ISSUE TITLE
a is null

### ISSUE THREAD

**Issue by ligi** [MyCryptoHQ/MyCrypto#1857]
### Description of the Issue

error when canceling scan in "parity signer flow"

### Steps to Reproduce

1. enter parity signer flow
2. click "Send Transaction"
3. click cancel 

### Console Logs / Screenshots
![selection_066](https://user-images.githubusercontent.com/111600/40608540-121ebcd2-626c-11e8-8c67-671f6ce862e7.png)

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/775227584579187)

**Comment by wtzb** [comment]
Thank you for opening this issue. Since this issue applies to an older, no longer supported version of MyCrypto, I'm closing this to keep a better overview of issues that are currently applicable.

If you believe this was in error, or if this issue still applies, please don't hesitate to comment or [reach out to us directly](https://support.mycrypto.com/contact-us). Thanks for helping us and letting us know of any issues you might run into!
