### ISSUE TITLE
Send Token confirmation popup should show contract in proper explorer 

### ISSUE THREAD

**Issue by alepc253** [MyCryptoHQ/MyCrypto#2012]
### Description of the Issue

When sending tokens in a non-ethereum network, it shouldn't link to etherscan.io in confirmation popup (this explorer should be a network parameter). 

### Steps to Reproduce

1. Choose RSK network
2. Access a wallet that have tokens
3. Prepare a token transaction
4. Check in confirmation popup that contract address is linked to etherscan.io
5. Click that link and check that the contract doesn't exist there

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/772183789713937)

**Comment by wtzb** [comment]
Thank you for opening this issue. Since this issue applies to an older, no longer supported version of MyCrypto, I'm closing this to keep a better overview of issues that are currently applicable.

If you believe this was in error, or if this issue still applies, please don't hesitate to comment or [reach out to us directly](https://support.mycrypto.com/contact-us). Thanks for helping us and letting us know of any issues you might run into!
