### ISSUE TITLE
Ledger now use BIP44 for accounts address derivation

### ISSUE THREAD

**Issue by gre** [MyCryptoHQ/MyCrypto#2070]
Hi, I'm gre from Ledger Live team.
Since Ledger Live release, Ledger is now derivating Ethereum and Ethereum Classic accounts by following BIP44 standard.

## what changes

Ledger Ethereum Chrome Wallet used to derive only one address at `m/44'/60'/0'/0` (NB: without the last `/0` of BIP44).
MEW/MyCrypto have so far followed this idea that Ledger's "root" is at `m/44'/60'/0'` and therefore have chosen to derive pages of addresses by using `m/44'/60'/0'/x` (where x is a value from 0 to +inf)

in Ledger Live instead, the idea is to follow BIP44, which means the first address is derived on `m/44'/60'/0'/0/0`, the second on `m/44'/60'/1'/0/0`, and so on,.. so in other words using the `account` field of BIP44. (`m/44'/60'/x'/0/0`)

### rationale

The benefit of this is that, as we increment an "hardened" path so it's more "secure" in term of privacy. We also use the same BIP44 convention for all cryptocurrencies so it unifies our approach and codebase.
The main change from your side is that, is as it's not a public derivation, you can't derive like you do, without the device, you will need to always ask the device to derive each address.

## current actions and workaround

Since our release, we've seen some users a bit confused by this. To cover these issues, we have been scanning both the "legacy" paths and the new paths (1.0.0). Moreover, a second workaround was added (1.0.2): we will also always scan the first 5 addresses of MyCrypto even if there are "empty" accounts in the middle.. because, as we follow BIP44, when scanning accounts is to stop at first account without transactions. *(the fact MEW allow users to take any arbitrary address from the pages have a cost. our tradeoff is so far to assume a user don't paginate more than the first page unless he have finished its account, which might still be not true,.. past first page, if users don't leave "empty" accounts and use the address in order, they should be fine)*

Finally, we are also helping our users discovering their new Ledger Live path in MyCrypto but this is getting a bit more hairy to explain to them. Basically you can use the "Custom field" and manually input: `m/44'/60'/0'/0` then select the first derived address (this is LedgerLive first account), then switch to `m/44'/60'/1'/0`, select the first address (this is LedgerLive second account), and so on..

But this is a temporary solution for now. I feel we should have a better option offered, right?

### what you could do

here is suggestion of what you could have:

- a new "Ledger Live" option that would derive the addresses using the hardened path. Not sure how reachable for you to paginate address like before you will always need the device and it can take some times to derive addresses (like 1-2s per page)
  - if you do so, please also follow BIP44 spec part that says: *Software should prevent a creation of an account if a previous account does not have a transaction history (meaning none of its addresses have been used before).*
- the previous Ledger option might be renamed as `Ledger (legacy)`

**Comment by gre** [comment]
@Arachnid 

I think the main reasons was

- the derivation path is consistent across all other cryptocurrencies (following BIP44).
- this offers more privacy because it's an hardened derivation
- (minor) only BIP44 seems to clearly state that you scan address in order, which does not seem the case for other choices? (MEW deliberately allow you to pick an address, not necessary "the next one")

is there any of the options that uses hardened derivation we were not aware?

**Comment by gre** [comment]
@Arachnid 

I think the main reasons was

- the derivation path is consistent across all other cryptocurrencies and is standard (following BIP44, so it's not something we invented).
- this offers more privacy because it's an hardened derivation
- (minor) only BIP44 seems to clearly state that you scan address in order, which does not seem the case for other choices? (MEW deliberately allow you to pick any address, not necessary "the next one")

is there any of the options that uses hardened derivation we were not aware?

**Comment by Arachnid** [comment]
> the derivation path is consistent across all other cryptocurrencies and is standard (following BIP44, so it's not something we invented).

BIP44 doesn't really fit Ethereum very well. As a result, there's already several mutually incompatible interpretations of which component to increment. I'm sure the MEW folks could summarise existing options for you.

> this offers more privacy because it's an hardened derivation

This is a nice benefit - but is it worth breaking compatibility with every other user of the scheme for it?

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/771983371770048)

**Comment by cburgdorf** [comment]
>We should make the old Ledger path available in the dropdown under  `Ledger - Legacy (ETH)`

@tayvano I came here to open an issue about that but then found this one. Currently the derivation path that people used when they bought and set up a ledger a while back isn't listed anymore. This may confuse a lot of people who are trying to access there account with their seed phrase (which they shouldn't in the first place but still it happens)

**Comment by DavidBueno77** [comment]
@cburgdorf that would be me.. 

I have not been able to move my EOS tokens in time. Super dumb, I know. 
Now, to move my eos, I need my ETH private key. I use MEW with ledger, so I dont have the private key..
I use https://iancoleman.io/bip39/ to create my keys fro my ledger seed, but I cant find the right adress. 

I am confused on how to set it right.. I dont know the account nr of my eth adres for exampe, and now reading into these posts only confuse me more..

Sorry if this is the wrong place for these questions, new to github.. hi!

**Comment by tayvano** [comment]
@DavidBueno77 Please email us at support@mycrypto.com and we'll help you out! Much easier than github!

**Comment by DavidBueno77** [comment]
Ok thanks! That would be great! Will do tonight..Verzonden vanaf mijn Samsung Galaxy-smartphone.
-------- Oorspronkelijk bericht --------Van: Taylor Monahan <notifications@github.com> Datum: 14-11-18  00:33  (GMT+01:00) Aan: MyCryptoHQ/MyCrypto <MyCrypto@noreply.github.com> Cc: DavidBueno77 <david@deepermedia.nl>, Mention <mention@noreply.github.com> Onderwerp: Re: [MyCryptoHQ/MyCrypto] Ledger now use BIP44 for accounts address
  derivation (#2070) @DavidBueno77 Please email us at support@mycrypto.com and we'll help you out! Much easier than github!

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/MyCryptoHQ/MyCrypto","title":"MyCryptoHQ/MyCrypto","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/MyCryptoHQ/MyCrypto"}},"updates":{"snippets":[{"icon":"PERSON","message":"@tayvano in #2070: @DavidBueno77 Please email us at support@mycrypto.com and we'll help you out! Much easier than github!"}],"action":{"name":"View Issue","url":"https://github.com/MyCryptoHQ/MyCrypto/issues/2070#issuecomment-438479138"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/MyCryptoHQ/MyCrypto/issues/2070#issuecomment-438479138",
"url": "https://github.com/MyCryptoHQ/MyCrypto/issues/2070#issuecomment-438479138",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [MyCryptoHQ/MyCrypto] Ledger now use BIP44 for accounts address derivation (#2070)",
"sections": [
{
"text": "",
"activityTitle": "**Taylor Monahan**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@tayvano",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"MyCryptoHQ/MyCrypto\",\n\"issueId\": 2070,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"MyCryptoHQ/MyCrypto\",\n\"issueId\": 2070\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/MyCryptoHQ/MyCrypto/issues/2070#issuecomment-438479138"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 356494117\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by twfink** [comment]
doesn't this page need an update too?
https://support.ledger.com/hc/en-us/articles/115005297709-Export-your-accounts

**Comment by timbeiko** [comment]
@wtzb is there anywhere we can follow progress on this? Thanks!

**Comment by Mrtenz** [comment]
@timbeiko This is supported in the current version of MyCrypto. If you're using the legacy desktop application, you can access your Ledger Live adresses by specifying the derivation path manually (e.g., `m/44'/60'/x'/0`, where `x` is the account index in Ledger Live).

**Comment by timbeiko** [comment]
@Mrtenz yeah, I was able to do that. I was wondering if there are plans to add it as part of the default UI so you don't have to manually copy/paste the derivation path.

**Comment by Mrtenz** [comment]
@timbeiko We don't actively add new features to the current desktop application, but this will be fully supported on the replacement we are working on!

**Comment by arnetheduck** [comment]
Hi! I'm looking to sign a message with a ledger-live-derived address, but the "sign message" section of the web site does not appear to support "ledger live" derivation paths - what am I missing? Importing for sending and receiving eth works fine.

**Comment by ekkis** [comment]
> The benefit of this is that, as we increment an "hardened" path so it's more "secure" in term of privacy

that sentence is malformed.  I think it means to say `The benefit of this is that we increment a "hardened" path so it's more "secure" in term of privacy`

**Comment by ekkis** [comment]
> The main change from your side is that, is as it's not a public derivation, you can't derive like you do, without the device, you will need to always ask the device to derive each address.

also broken.  perhaps:

> The main change from your side is that, as it's not a public derivation, you can't derive without the device. You will need to always ask the device to derive each address.

**Comment by ekkis** [comment]
> because, as we follow BIP44, when scanning accounts is to stop at first account without transactions

it's hard to understand this language.  I think it means:

> because, as we follow BIP44, when scanning accounts we are supposed to stop at first the account without transactions

**Comment by gre** [comment]
@ekkis you are correct. I should have proofread myself a bit more. Let me know if you need more information or clarification.

**Comment by ekkis** [comment]
> @ekkis you are correct. I should have proofread myself a bit more. Let me know if you need more information or clarification.

no worries.  there are more corrections needed but I will finish proof-reading a bit later
