### ISSUE TITLE
Reading contracts - if return type is address[], the return value is not prefixed with  0x

### ISSUE THREAD

**Issue by rstormsf** [MyCryptoHQ/MyCrypto#2075]
If a contract's ABI returns `address[]` type, it doesn't show it with 0x prefix.

![image](https://user-images.githubusercontent.com/9360827/42778847-52a2158a-88f3-11e8-8318-27b07a2d162b.png)

**Comment by ConnorBryan** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/766176255632807)

**Comment by wtzb** [comment]
Thank you for opening this issue! While this issue is still present on our current site, the work we're doing on the new version of MyCrypto should make it obsolete. Please come check out the beta [here](https://beta.mycrypto.com/).

If you believe this was in error, or if this issue still applies, please don't hesitate to comment or [reach out to us directly](https://support.mycrypto.com/contact-us). Thanks for helping us and letting us know of any issues you might run into!
