### ISSUE TITLE
red crash screen when using TREZOR: "failed to execute 'removeChild' of 'Node': The node to be removed is not a child of this node."

### ISSUE THREAD

**Issue by k06a** [MyCryptoHQ/MyCrypto#2078]
Got this screenshot from friend:

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/702124/42822638-3d00ba0a-89e4-11e8-909f-5aa19f8a033d.png">

**Comment by tayvano** [comment]
@k06a Thanks for the report

Can you please ask your friend: 

- What was he trying to do when he encountered the error?

- Was he using Google Chrome?

- Was he on a Mac or a PC or Linux?

**Comment by k06a** [comment]
1. He just entered Trezor password
2. Yes, Google Chrome
3. Mac

**Comment by tayvano** [comment]
Hmm interesting. Possibly related to https://github.com/MyCryptoHQ/MyCrypto/issues/2080 even though the errors are different...

**Comment by ConnorBryan** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/766176255632800)

**Comment by wtzb** [comment]
Thank you for opening this issue. Since this issue applies to an older, no longer supported version of MyCrypto, I'm closing this to keep a better overview of issues that are currently applicable.

If you believe this was in error, or if this issue still applies, please don't hesitate to comment or [reach out to us directly](https://support.mycrypto.com/contact-us). Thanks for helping us and letting us know of any issues you might run into!
