### ISSUE TITLE
Red Crash Screen: cannot read property 'muln' of null

### ISSUE THREAD

**Issue by tjayrush** [MyCryptoHQ/MyCrypto#2080]
<img width="596" alt="screen shot 2018-07-18 at 9 05 27 am" src="https://user-images.githubusercontent.com/5417918/42883506-c99dfcb8-8a69-11e8-925e-cae91bac99de.png">

If you're having an issue with unlocking your wallet, a transaction, a swap,
or an ENS auction, please email support@mycrypto.com. Github issues are for
development only, and support questions that aren't bugs or feature requests
will not be answered.

---

If you've experienced a bug, please provide the following information:

### Description of the Issue

Opened the 'Switch Wallet' link at top of page when viewing a regular wallet. Clicked on 

### Steps to Reproduce

(Explain how you got this issue)

### Description of Your Machine

(Your browser, browser version, operating system, device)

### Console Logs / Screenshots

(Console logs or screenshots go here, if applicable)

---

If you're suggesting a feature, make sure someone hasn't already posted it. If
no one has, please provide the following information:

### Description of the Feature

(Your description goes here)

### Example(s) of Feature

(If another product or app is doing this, please link it)

**Comment by ConnorBryan** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/766176255632800)

**Comment by wtzb** [comment]
Thank you for opening this issue. Since this issue applies to an older, no longer supported version of MyCrypto, I'm closing this to keep a better overview of issues that are currently applicable.

If you believe this was in error, or if this issue still applies, please don't hesitate to comment or [reach out to us directly](https://support.mycrypto.com/contact-us). Thanks for helping us and letting us know of any issues you might run into!
