### ISSUE TITLE
RSK estimated minimum gas price

### ISSUE THREAD

**Issue by ilanolkies** [MyCryptoHQ/MyCrypto#2081]
Network configurations force gas price to be static. **RSK gas price should be estimated** and not static.

RSK minimum gas price is defined by miners and can variate along time. This variation is described in [RSKIP-09](https://github.com/rsksmart/RSKIPs/blob/master/IPs/RSKIP09.md).

This estimation should be derived from the latest block minimum gas price.

**Comment by ilanolkies** [comment]
Hi! We are trying to estimate gas price settings for RSK. To do this we need to get the latest block minimum gas price. 

We tried adding the RPC endpoint to `INode` and call it from `fetchEstimates()`, but when executing `node.getCurrentMinGasPrice` evaluates _undefined_:

```javascript
const node: INode = yield select(configNodesSelectors.getNodeLib);
const _minGasPrice: string = yield apply(node, node.getCurrentMinGasPrice);
```

Is it necessary to add this endpoint to [shepherd](https://github.com/MyCryptoHQ/shepherd) package? Is there any other way to make this RPC call the right way?

**Comment by tayvano** [comment]
Hi @ilanolkies. Thanks for looking into this. I personally can't help you and it's the weekend but I'll try to get you an answer as soon as reasonably possible. 

@HenryNguyen5 will probably be the one with the best insights into this. Correct me if I'm wrong, Henry. 

Thanks

**Comment by HenryNguyen5** [comment]
Hi @ilanolkies, your best bet is to wrap the node instance with a proxy, similar to how we do it with fetching token balances since `getCurrentMinGasPrice` really just calls `getCurrentBlock` under the hood and accesses a property on the return result.

Please see the following to get an example of how to wrap the instance in a proxy with the correct typings: https://github.com/MyCryptoHQ/MyCrypto/blob/develop/common/libs/nodes/tokenBalanceProxy.ts
https://github.com/MyCryptoHQ/MyCrypto/blob/develop/common/libs/nodes/INode.ts
https://github.com/MyCryptoHQ/MyCrypto/blob/develop/common/libs/nodes/index.ts

**Comment by ilanolkies** [comment]
@HenryNguyen5 actual implemented `getCurrentBlock` requests `eth_blockNumber`. This is not sufficient.

**Comment by HenryNguyen5** [comment]
Ah, then an additional method will need to be implemented on shepherd side to allow for the `eth_getBlockByNumber` method. You can use this PR as a reference: https://github.com/MyCryptoHQ/shepherd/pull/9/files

**Comment by ilanolkies** [comment]
@HenryNguyen5 I updated the last comment, sory.

**Comment by ilanolkies** [comment]
@HenryNguyen5 Ok! I will work on shepherd if needed.

**Comment by ilanolkies** [comment]
Hi @HenryNguyen5 ! I'm trying to use the new shephard provider method, adding it manually to the node module. 

I tried to replicate other queries (like transaction or balance) and I was not able to get any result.
I'm still getting `undefined` as explained in the first comment.

Do you have any PR as a reference? 
Thanks!

**Comment by ConnorBryan** [comment]
@HenryNguyen5 @ilanolkies  Any update?

[Added to Asana](https://app.asana.com/0/763966770926912/766176255632797)

**Comment by ilanolkies** [comment]
@ConnorBryan waiting for https://github.com/MyCryptoHQ/shepherd/pull/68 to be merged...

**Comment by wtzb** [comment]
Thank you for opening this issue! While this issue is still present on our current site, the work we're doing on the new version of MyCrypto should make it obsolete. Please come check out the beta [here](https://beta.mycrypto.com/).

If you believe this was in error, or if this issue still applies, please don't hesitate to comment or [reach out to us directly](https://support.mycrypto.com/contact-us). Thanks for helping us and letting us know of any issues you might run into!
