### ISSUE TITLE
Update Ledger error message to include link to knowledge base article with troubleshooting tips.

### ISSUE THREAD

**Issue by logonaut** [MyCryptoHQ/MyCrypto#2082]
### Description of the Issue

Failure to recognize Ledger Nano S status

### Steps to Reproduce

When attempting to Connect to Ledger Wallet, I receive the error message "Your Ledger is currently in use with another application. Please wait, or close other wallet applications before trying again." Ledger is not currently in use, however, and in fact is not even connected to the computer yet.

### Description of Your Machine

MacBook Pro (Retina, 13-inch, Late 2013), macOS Sierra v10.12.6, MyCrypto Desktop for Mac v1.2.1

**Comment by logonaut** [comment]
Issue resolved after discovering that browser support was not disabled on Ledger.

**Comment by tayvano** [comment]
To make everyone's life easier, we should add a link to in this error message with the common troubleshooting tips. This error has been popping up more and more frequently, probably due to the browser support needing to be on for mycrypto.com and off for the desktop application. 

Best kb article is probably https://support.mycrypto.com/hardware-wallets/ledger-hardware-wallet-unable-to-connect-on-mycrypto.html  -- i just opened a PR over there to improve it further.

**Comment by ConnorBryan** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/764146476480802)

**Comment by collac** [comment]
I've tried all the possible solutions descrived avobe and on the Mycrypto page, however, the new update on the Ledger removes the browser support setting. As I try using t with the desktop app it gives me this message :"  Your Ledger is currently in use with another application. Please wait, or close other wallet applications before trying again." NOt possible as I restarted my pc and didnt start anything related to the  ledger. Where should I look for more options to try. TIA

**Comment by CBobRobison** [comment]
I'm having the same issue as @collac

**Comment by wtzb** [comment]
Thank you for opening this issue. Since this issue applies to an older, no longer supported version of MyCrypto, I'm closing this to keep a better overview of issues that are currently applicable.

If you believe this was in error, or if this issue still applies, please don't hesitate to comment or [reach out to us directly](https://support.mycrypto.com/contact-us). Thanks for helping us and letting us know of any issues you might run into!
