### ISSUE TITLE
Wrong rate for RSK

### ISSUE THREAD

**Issue by alepc253** [MyCryptoHQ/MyCrypto#2091]
### Description of the Issue

MyCrypto API is taking SBTC as "SuperBitcoin" (or another coin) instead of "SmartBitcoin" from RSK.
SBTC is pegged 1:1 to BTC, so that must be the rate.
Users may think that they are paying far less than what they are actually paying (in USD).

This is used in `common/api/rates.ts`.

### Steps to Reproduce

a) Select RSK network and check any fee conversion to USD, or
b) Check `https://proxy.mycryptoapi.com/cc/price?fsym=ETH&tsyms=SBTC` conversion or `https://proxy.mycryptoapi.com/cc/price?fsym=BTC&tsyms=SBTC`

**Comment by wbobeirne** [comment]
MyCrypto's rates are just sourced from CryptoCompare's API (https://www.cryptocompare.com/) via a proxy server. Unfortunately since there's already a SBTC that they provide rates for, there's no way to disambiguate. There are only a few ways to work this out that I see:

1. Disable equivalent values when on the RSK network. The same is done for testnets to prevent confusion.
2. Try to work something out with CryptoCompare. However, seeing as SBTC has a decent amount of volume, and I don't think RSK's SBTC is on any exchanges yet (correct me if I'm wrong) I don't think that'll likely result in anything.
3. RSK's token changes its ticker to something that isn't already taken. If the plan is to get it trading at some point, this collision will keep coming up on other exchanges. Better to rip the band-aid off sooner rather than later.

**Comment by ConnorBryan** [comment]
Closing as out of scope.

**Comment by alepc253** [comment]
Hi guys @wbobeirne @ConnorBryan, are you still considering the PR that we made because of this issue?
