### ISSUE TITLE
Migrate to Trezor Connect v5

### ISSUE THREAD

**Issue by ghost** [MyCryptoHQ/MyCrypto#2093]
TREZOR remade the whole library from scratch

https://github.com/trezor/connect/tree/v5

@dternyak @ConnorBryan @HenryNguyen5 @wbobeirne

**Comment by ConnorBryan** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/763966770926921)

**Comment by wtzb** [comment]
Thank you for opening this issue. Since this issue applies to an older, no longer supported version of MyCrypto, I'm closing this to keep a better overview of issues that are currently applicable.

If you believe this was in error, or if this issue still applies, please don't hesitate to comment or [reach out to us directly](https://support.mycrypto.com/contact-us). Thanks for helping us and letting us know of any issues you might run into!
