### ISSUE TITLE
Installing MetaMask after navigating to metamask wallet unlock error

### ISSUE THREAD

**Issue by Azarielle** [MyCryptoHQ/MyCrypto#2105]
Web app does not detect the app if you install it after navigating to Wallet unlock via MetaMask 

![image](https://user-images.githubusercontent.com/25834495/44061709-93450f76-9f27-11e8-8cba-28e591b3c115.png)

**Comment by hahnmichaelf** [comment]
I believe this is due to the way MetaMask injects the code required to make it operate. This occurs after pageload, so it wouldn't do so when it was just installed. Maybe what can be done is to indicate that in the error displayed in your image.

Perhaps: "Web3 not found. Please check that MetaMask is installed. If it is already installed, try refreshing your MyCrypto page." or something similar.

**Comment by Azarielle** [comment]
[Added to Asana](https://app.asana.com/0/763966770926912/779983315837165)
