### ISSUE TITLE
Gas Limit not updated automatically for token, causes wrong "send all" amount

### ISSUE THREAD

**Issue by voldemarz** [MyCryptoHQ/MyCrypto#2128]
### Description of the Issue

When you expand "Advanced" section AFTER having filled the address and amount the Gas Limit doesn't update automatically even though the checkbox to do it is set. Then when try to send tokens that require higher than default gas limit the transaction will fail with "Error: intrinsic gas too low". 

If Metamask was used this causes its transaction confirmation window to remain open with a loading circle which easily can cause confusion later if not noticed. Not sure if that is due to MyCrypto or Metamask.

After token transaction failure all fields are cleared (which is annoying, especially the address). Now after the transaction failure, the token is stills selected in asset type dropdown, but when press on arrow in the amount field to "send all" it actually filled with the amount of ether in the wallet.

### Steps to Reproduce

1. Log into MyCrypto wallet
2. Fill in fields for for sending some tokens that require higher than default gas limit. Specifically in this case used Telcoin (contract https://etherscan.io/address/0x85e076361cc813a908ff672f9bad1541474402b2)
3. AFTER filling the address and amount expand Advanced field. Do not modify anything there. Assuming "Automatically Calculate Gas Limit" is ticked as per default.
4. Send transaction
5. After transaction failure try to use "send all" arrow button in amount field for the token. Notice incorrectly derived amount.

### Description of Your Machine
Google Chrome 68.0.3440.84 (Official Build) (64-bit), Windows 10

**Comment by wtzb** [comment]
Thank you for opening this issue! While this issue is still present on our current site, the work we're doing on the new version of MyCrypto should make it obsolete. Please come check out the beta [here](https://beta.mycrypto.com/).

If you believe this was in error, or if this issue still applies, please don't hesitate to comment or [reach out to us directly](https://support.mycrypto.com/contact-us). Thanks for helping us and letting us know of any issues you might run into!
