### ISSUE TITLE
Keystore Support is non-universal

### ISSUE THREAD

**Issue by ChosunOne** [MyCryptoHQ/MyCrypto#2131]
### Description of the Issue

Loaded keystore files do not support files generated from web3js v3 encrypted wallets.  

### Steps to Reproduce

Create a wallet via the following code in Web3js:
```
var wallet = require("ethereumjs-wallet")
let private_key = Buffer.from([0x75, 0xca, 0x59, 0x3e, 0xcb, 0x74, 0x06, 0x79, 0x19, 0x10, 0xff, 0x87, 0x0d, 0x0f, 0x8d, 0xd0,0x4d, 0x13, 0x00, 0xf2, 0xc0, 0xfd, 0x17, 0xaf,0xa6, 0xff, 0xbb, 0x60, 0x51, 0xbf, 0x4a, 0xc2])
let salt = Buffer.from([0xae, 0x3c, 0xd4, 0xe7, 0x01, 0x38, 0x36, 0xa3,0xdf, 0x6b, 0xd7, 0x24, 0x1b, 0x12, 0xdb, 0x06,0x1d, 0xbe, 0x2c, 0x67, 0x85, 0x85, 0x3c, 0xce,0x42, 0x2d, 0x14, 0x8a, 0x62, 0x4c, 0xe0, 0xbd])
let iv = Buffer.from([0x60, 0x87, 0xda, 0xb2, 0xf9, 0xfd, 0xbb, 0xfa,0xdd, 0xc3, 0x1a, 0x90, 0x97, 0x35, 0xc1, 0xe6])
let ether_wallet = wallet.fromPrivateKey(private_key)
let options = {salt, iv, kdf: 'scrypt', cipher: 'aes-128-cbc'}
ether_wallet.toV3("testpassword", options)
```
which will generate a wallet like the following:
```
{ version: 3,
  id: '2a6ccdc7-18cf-477e-86b7-f40b4b4b91e7',
  address: '89e07f904e53d9604261698e87c69146b9acb79c',
  crypto:
   { ciphertext:
      '052643cd39cd9e2e0f045ebcfec424d33a9fa6135f363d94a95cb09abc4d086a1c7eecc132c966e2a6691c6640605615',
     cipherparams: { iv: '6087dab2f9fdbbfaddc31a909735c1e6' },
     cipher: 'aes-128-cbc',
     kdf: 'scrypt',
     kdfparams:
      { dklen: 32,
        salt:
         'ae3cd4e7013836a3df6bd7241b12db061dbe2c6785853cce422d148a624ce0bd',
        n: 262144,
        r: 8,
        p: 1 },
     mac:
      '44c8b015c8702b9a315644725ca2c780605d62f56583ec43c140c14860ef807a' } }
```
you can then load this json using something like:
```
let other_wallet = wallet.fromV3(ether_wallet_json, "testpassword")
```
which will successfully decrypt the key and generate a wallet.  

Attempting to load this keystore in the Desktop Mycrypto app however will give an invalid password error.  

### Description of Your Machine

Ubuntu 18.04 LTS

**Comment by hahnmichaelf** [comment]
Hey @ChosunOne, is the exact error you're receiving "Please enter a valid password"? The reason why this isn't working is because its not a valid json file. I was able to get this working using the same method you used with one modification. 

The output would look like this (note this is similar to the output when you generate a keystore using our desktop app):

`{"version":3,"id":"2dcc6a03-2ca6-4fb3-a8ce-0d6890e347a0","address":"89e07f904e53d9604261698e87c69146b9acb79c","crypto":{"ciphertext":"052643cd39cd9e2e0f045ebcfec424d33a9fa6135f363d94a95cb09abc4d086a1c7eecc132c966e2a6691c6640605615","cipherparams":{"iv":"6087dab2f9fdbbfaddc31a909735c1e6"},"cipher":"aes-128-cbc","kdf":"scrypt","kdfparams":{"dklen":32,"salt":"ae3cd4e7013836a3df6bd7241b12db061dbe2c6785853cce422d148a624ce0bd","n":262144,"r":8,"p":1},"mac":"44c8b015c8702b9a315644725ca2c780605d62f56583ec43c140c14860ef807a"}}`

The edits I made are marked with double-asterisks: 

```
var wallet = require("ethereumjs-wallet")
**var fs = require('fs')**
let private_key = Buffer.from([0x75, 0xca, 0x59, 0x3e, 0xcb, 0x74, 0x06, 0x79, 0x19, 0x10, 0xff, 0x87, 0x0d, 0x0f, 0x8d, 0xd0,0x4d, 0x13, 0x00, 0xf2, 0xc0, 0xfd, 0x17, 0xaf,0xa6, 0xff, 0xbb, 0x60, 0x51, 0xbf, 0x4a, 0xc2])
let salt = Buffer.from([0xae, 0x3c, 0xd4, 0xe7, 0x01, 0x38, 0x36, 0xa3,0xdf, 0x6b, 0xd7, 0x24, 0x1b, 0x12, 0xdb, 0x06,0x1d, 0xbe, 0x2c, 0x67, 0x85, 0x85, 0x3c, 0xce,0x42, 0x2d, 0x14, 0x8a, 0x62, 0x4c, 0xe0, 0xbd])
let iv = Buffer.from([0x60, 0x87, 0xda, 0xb2, 0xf9, 0xfd, 0xbb, 0xfa,0xdd, 0xc3, 0x1a, 0x90, 0x97, 0x35, 0xc1, 0xe6])
let ether_wallet = wallet.fromPrivateKey(private_key)
let options = {salt, iv, kdf: 'scrypt', cipher: 'aes-128-cbc'}
**fs.writeFileSync("wallet",JSON.stringify(ether_wallet.toV3("testpassword", options)))**
```

JSON.stringify() should allow you to create a compatible wallet. I have tested this and verified that it works.

**Comment by ChosunOne** [comment]
Ah I see, I wasn't aware it depended on writing without any of the spaces.
