### ISSUE TITLE
Slider for gasprice doesn't show tooltip for RSK

### ISSUE THREAD

**Issue by herrerameri** [MyCryptoHQ/MyCrypto#2180]
### Description of the Issue
Slider for gasprice doesn't show a number inside the tooltip when using RSK. 

### Steps to Reproduce
1. Open an RSK wallet with MyCrypto (I tried it with Trezor and Mnemonic in both, mobile and desktop versions)
2. Move the slide for gasprice
3. Look at the tooltip, it's entirely black 
4. Then, if you expand the Advanced options, you'll see that gasprice is calculating right 

### Console Logs / Screenshots
![screenshot from 2018-09-18 14-42-07](https://user-images.githubusercontent.com/22835487/45974109-c8793400-c016-11e8-827d-24b0502db344.png)

**Comment by tayvano** [comment]
Related to https://github.com/MyCryptoHQ/MyCrypto/issues/2215

**Comment by wtzb** [comment]
Thank you for opening this issue! While this issue is still present on our current site, the work we're doing on the new version of MyCrypto should make it obsolete. Please come check out the beta [here](https://beta.mycrypto.com/).

If you believe this was in error, or if this issue still applies, please don't hesitate to comment or [reach out to us directly](https://support.mycrypto.com/contact-us). Thanks for helping us and letting us know of any issues you might run into!
