### ISSUE TITLE
Add Support for Wanchain

### ISSUE THREAD

**Issue by gedanziger** [MyCryptoHQ/MyCrypto#2181]
### Add Wanchain Support

I was going to add in Wanchain support as well to the MyCrypto wallet on my personal fork. I checked the contributor guide and figured I'd leave an issue here so you have a heads up that I'm working on it. Then if everything looks cool later I might open a PR in and see what you guys think.

**Comment by tayvano** [comment]
Would love to add support for Wanchain. I know there are a ton of people on Reddit who are a bit confused, etc. 

Let us know if we can assist

**Comment by tayvano** [comment]
Hey—just wondering if this is something you are still working on. I never fully understood the differences in Wanchain and Ethereum-based networks.

**Comment by wtzb** [comment]
Thank you for opening this issue. Since this issue applies to an older, no longer supported version of MyCrypto, I'm closing this to keep a better overview of issues that are currently applicable.

If you believe this was in error, or if this issue still applies, please don't hesitate to comment or [reach out to us directly](https://support.mycrypto.com/contact-us). Thanks for helping us and letting us know of any issues you might run into!
