### ISSUE TITLE
Potential memory leaks, unstable behavior when making too many RPC calls

### ISSUE THREAD

**Issue by rstormsf** [MyCryptoHQ/MyCrypto#2214]
Steps. 
1. Open latest build myCrypto desktop for Mac OSX (7hrs ago released)
https://github.com/MyCryptoHQ/MyCrypto/releases/download/1.4.0/mac_1.4.0_MyCrypto.dmg
2. Connect with ledger
3. Besides opening ETH also use some token, so that it should load both balances
4. Try to move to next page
Result:
MyCrypto becomes unstable and frozen. 
![image](https://user-images.githubusercontent.com/9360827/47063114-b52d3480-d18e-11e8-8278-b10faf144dc5.png)

I believe myCrypto is trying to make too many RPC calls and becomes unresponsive
@ConnorBryan

**Comment by tayvano** [comment]
@rstormsf We fixed a couple semi-related issues to this that potentially fixed this issue. Please let me know if you are still experiencing the issue and we'll do further research.

**Comment by wtzb** [comment]
Thank you for opening this issue! While this issue is still present on our current site, the work we're doing on the new version of MyCrypto should make it obsolete. Please come check out the beta [here](https://beta.mycrypto.com/).

If you believe this was in error, or if this issue still applies, please don't hesitate to comment or [reach out to us directly](https://support.mycrypto.com/contact-us). Thanks for helping us and letting us know of any issues you might run into!
