### ISSUE TITLE
No tooltip when on custom network for selecting tx fee

### ISSUE THREAD

**Issue by rstormsf** [MyCryptoHQ/MyCrypto#2215]
![image](https://user-images.githubusercontent.com/9360827/47063628-c4ad7d00-d190-11e8-9214-46f4ab51057f.png)

**Comment by wtzb** [comment]
Thank you for opening this issue! While this issue is still present on our current site, the work we're doing on the new version of MyCrypto should make it obsolete. Please come check out the beta [here](https://beta.mycrypto.com/).

If you believe this was in error, or if this issue still applies, please don't hesitate to comment or [reach out to us directly](https://support.mycrypto.com/contact-us). Thanks for helping us and letting us know of any issues you might run into!
