### ISSUE TITLE
Please add X button to skip modal on the front

### ISSUE THREAD

**Issue by ghost** [MyCryptoHQ/MyCrypto#2229]

**Comment by blurpesec** [comment]
@tayvano @Sonicrida @ConnorBryan @nickmccurdy Was this something that we wanted to do, or did we want to keep the slight friction to add a possibility that people will read it and understand how important security is? Personally, I think we should keep the friction in place...

**Comment by tayvano** [comment]
We keep going back and forth on it in the design meetings. I prefer to keep the friction, even though it is less necessary now that we don't have PKs on the web anymore. Regardless, its super low priority and probably won't be done until we make larger revisions to the onboarding flow.

**Comment by nickmccurdy** [comment]
I think we should add a close button. Without it, it's more difficult for users with vision, motor, and mental disabilities to navigate through the onboarding flow. I'm concerned that if a user with accessibility issue uses incognito, it may slow them down significantly enough that they may need to stop using incognito or block the popup. The popup will still be prominent if we add a close button.

In the future, I'd like us to move away from modals and have this content inlined into the appropriate pages. For example in game design you'll often want to tell the player the combat buttons in the first fight that they need to use the buttons on an enemy, rather than having a large tutorial that can be too much information at once and slows down the player's self-discovery of the game. Having inline information also makes it easier to remember security tips without having to reopen the onboarding flow, while also interrupting user progress less.

**Comment by wtzb** [comment]
Thank you for opening this issue! While this is still present on our current site, the work we're doing on the new version of MyCrypto should make it obsolete. Please come check out the beta [here](https://beta.mycrypto.com/).

Thanks for helping us and letting us know of any feedback you might have, it's really appreciated.
