### ISSUE TITLE
Add custom token fails

### ISSUE THREAD

**Issue by alepc253** [MyCryptoHQ/MyCrypto#2285]
### Description of the Issue

When you want to add a custom token, the form shows the correct data but fails on saving.

### Steps to Reproduce

Go to Add Custom Token form, paste an ERC20 address and click "Save".

**Comment by sammy007** [comment]
So apparently it's not an issue if there is no solution for 1 year /s.

**Comment by wtzb** [comment]
Thank you for opening this issue! While this issue is still present on our current site, the work we're doing on the new version of MyCrypto should make it obsolete. Please come check out the beta [here](https://beta.mycrypto.com/).

If you believe this was in error, or if this issue still applies, please don't hesitate to comment or [reach out to us directly](https://support.mycrypto.com/contact-us). Thanks for helping us and letting us know of any issues you might run into!
