### ISSUE TITLE
Error in tx not found message for RSK network

### ISSUE THREAD

**Issue by jonathansmirnoff** [MyCryptoHQ/MyCrypto#2354]
### Description of the Issue

When a transaction is not found in RSK network the error message suggests to select another ETH node. This is an error. It shouldn't suggest that.

### Steps to Reproduce

1. Generate a transaction with an incorrect nonce. So the transaction will be rejected.
2. Go to "Check Transaction Status" or "Recent Transactions"
3. Try to access to the transaction information.
4. You'll get the message "Transaction Not Found"

### Expected behaviour

It shouldn't suggest to connect to another ETH node:
"Please use the dropdown in the top-right & select a different ETH node (e.g. ETH (Etherscan.io) or ETH (Infura.io) or ETH (MyCrypto)) and check again."

<img width="837" alt="screen shot 2019-01-11 at 16 14 19" src="https://user-images.githubusercontent.com/7558841/51056915-e1582600-15c2-11e9-8c99-9a97833af2a8.png">

**Comment by wtzb** [comment]
Thank you for opening this issue. Since this issue applies to an older, no longer supported version of MyCrypto, I'm closing this to keep a better overview of issues that are currently applicable.

If you believe this was in error, or if this issue still applies, please don't hesitate to comment or [reach out to us directly](https://support.mycrypto.com/contact-us). Thanks for helping us and letting us know of any issues you might run into!
