### ISSUE TITLE
Cannot use a mnemonic phrase with a custom network in MyCrypto app

### ISSUE THREAD

**Issue by ismaelbej** [MyCryptoHQ/MyCrypto#2370]
### Description of the Issue

Cannot use a mnemonic phrase with a custom network in MyCrypto app.

### Steps to Reproduce

1. Create a custom network
2. Mnemonic wallet is disabled in wallet selection 

### Description of Your Machine

Windows 7 x64, RAM 16Gb, Intel core i5 4440.

### Other tests

* Open a mnemonic wallet connected to Ethereum mainnet works correctly
* Using "view address" it shows the balance correctly

**Comment by blurpesec** [comment]
Hey Ismael,

We've specifically got it set up so that unsafe methods for accessing funds aren't available when on the website. If you're using the website to set up your custom network and node, then it will have the issue where it disallows private key, keystore file, and mnemonic phrase methods of access. 

Are you using the website or the [desktop application](https://download.mycrypto.com) for interacting with your custom network?

**Comment by ismaelbej** [comment]
Hi @blurpesec! I tested with the desktop app, but it is also disabled. Looking at the code it seem for mnemonic wallets it is expecting a derivation path but since it is a custom network it will fail.

**Comment by wtzb** [comment]
Thank you for opening this issue! While this issue is still present on our current site, the work we're doing on the new version of MyCrypto should make it obsolete. Please come check out the beta [here](https://beta.mycrypto.com/).

If you believe this was in error, or if this issue still applies, please don't hesitate to comment or [reach out to us directly](https://support.mycrypto.com/contact-us). Thanks for helping us and letting us know of any issues you might run into!
