### ISSUE TITLE
Deep link to prefill contract interaction options

### ISSUE THREAD

**Issue by ilanolkies** [MyCryptoHQ/MyCrypto#2381]
### Motivation
Developing dApps, it is necessary to have different types of active payment. The integration of MyCrypto would be much easier if, in a single click, you can take the user to the page or desktop app of contract interaction with all fields already prefilled. Checking out any contract function would be just one click.

### Description of the Feature
- Add deep links to select existing contracts, functions and then prefill forms.
- Add deep link to access custom contact, fetch ABI, select a function and prefill forms.

**Comment by ilanolkies** [comment]
Hi! Is there any news about this?

**Comment by wtzb** [comment]
Thank you for opening this issue! While this is still present on our current site, the work we're doing on the new version of MyCrypto should make it obsolete. Please come check out the beta [here](https://beta.mycrypto.com/).

https://github.com/MyCryptoHQ/MyCrypto/pull/2920

Thanks for helping us and letting us know of any ideas you might have, as it really helps us improve our product. I'm closing this issue here, but please know that we really appreciate any feedback you might have :)
