### ISSUE TITLE
Transaction Status - Data line break

### ISSUE THREAD

**Issue by ilanolkies** [MyCryptoHQ/MyCrypto#2383]
https://github.com/MyCryptoHQ/MyCrypto/blob/0776cc79ef1da333ea24cafb66cb4236f6467a3f/common/components/TransactionStatus/TransactionDataTable.tsx#L156

Transaction data would be easier to read if text breaks line instead of overflowing x.

<img width="1355" alt="screen shot 2019-02-11 at 14 49 24" src="https://user-images.githubusercontent.com/36084092/52582940-244d2980-2e0d-11e9-9c76-9771522a9a61.png">

**Comment by wtzb** [comment]
Thank you for opening this issue. Since this issue applies to an older, no longer supported version of MyCrypto, I'm closing this to keep a better overview of issues that are currently applicable.

If you believe this was in error, or if this issue still applies, please don't hesitate to comment or [reach out to us directly](https://support.mycrypto.com/contact-us). Thanks for helping us and letting us know of any issues you might run into!
