### ISSUE TITLE
Wrong validation message on address book

### ISSUE THREAD

**Issue by ilanolkies** [MyCryptoHQ/MyCrypto#2386]
### Description of the Issue

The validation message for wrong addresses displayed when adding a new address to the book shows a wrong network 

### Steps to Reproduce

1. Go to RSK network
2. Try to add an invalid address

### Description of Your Machine

Browser and Mac desktop

### Console Logs / Screenshots

<img width="1335" alt="screen shot 2019-02-15 at 15 42 26" src="https://user-images.githubusercontent.com/36084092/52877608-46121d80-3139-11e9-9555-1ad33103ffa6.png">

**Comment by kevinmonahan** [comment]
Cancel

**Comment by ilanolkies** [comment]
Hi! Any news? Thanks.

**Comment by wtzb** [comment]
Thank you for opening this issue! While this is still present on our current site, the work we're doing on the new version of MyCrypto should make it obsolete. Please come check out the beta [here](https://beta.mycrypto.com/).

Thanks for helping us and letting us know of any ideas you might have, as it really helps us improve our product. I'm closing this issue here, but please know that we really appreciate any feedback you might have :)
