### ISSUE TITLE
"Lost connection" message appears when connection wasn't actually lost

### ISSUE THREAD

**Issue by jspence425** [MyCryptoHQ/MyCrypto#2466]
From psnotadev#2000 on Discord:

> I get "You’ve lost your connection to the network, check your internet connection or try changing networks from the dropdown at the top right of the page." error if I im using another app for just a little while.  machine didnt go in sleep mode.  Usually it says the connection is restored.  but its another notification i need to dismiss to be able to see the work area

> running Version 1.6.0 (1.6.0)

**Comment by p-s-dev** [comment]
Running local node Parity-Ethereum/v2.3.7-stable-7d1415a-20190320/x86_64-linux-gnu/rustc1.33.0
MyCrypto desktop 1.6.3
login w ledger, select address, address loads fine.  as soon as I click "Scan for tokens" it immediately pops up "You’ve lost your connection to the network, check your internet connection or try changing networks from the dropdown at the top right of the page."  Then ~5-10s later it says the network is restored.  Clicking "Try Again" repeats the loop... near immediate "lost connection" then about the time the spinner stops it says connection restored.  
At least with "local node Parity-Ethereum/v2.3.7-stable" loading tokens seems totally broken.

**Comment by p-s-dev** [comment]
worth noting, loading tokens works fine when connected to Infura

**Comment by wtzb** [comment]
While this is still present on our current site, the work we're doing on the new version of MyCrypto should make it obsolete. Please come check out the beta [here](https://beta.mycrypto.com/).

Thanks for helping us and letting us know of any issues you might run into, as it really helps us improve our product. I'm closing this issue here, but please know that we really appreciate any feedback you might have :)
