### ISSUE TITLE
Error messages inconsistent between light and dark theme

### ISSUE THREAD

**Issue by voldemarz** [MyCryptoHQ/MyCrypto#2486]
### Description of Issue
Error messages are not the same in light and dark theme. I noticed when creating bug report for https://github.com/MyCryptoHQ/MyCrypto/issues/2485

See posted screenshots below with error messages after following repro steps as outlined in the issue linked above.

### What exactly were you doing when you encountered this issue?
See https://github.com/MyCryptoHQ/MyCrypto/issues/2485

### How were you accessing your wallet?
Ledger Nano S (Firmware 1.4.2, MCU 1.6)

### Description of Your Machine
Browser: Google Chrome
Browser version: Version 73.0.3683.103 (Official Build) (64-bit)
Operating system: Windows 10 (version 1803)
Device: Reproduced on 2 different PCs
MyCrypto.com

### Console Logs / Screenshots
![mcr1](https://user-images.githubusercontent.com/1264210/55676498-b4bc5d80-58d6-11e9-8956-585afa1679f5.png)
![mcr2](https://user-images.githubusercontent.com/1264210/55676499-b71eb780-58d6-11e9-9ee3-be10bb38c1dc.png)
![mcr3](https://user-images.githubusercontent.com/1264210/55676500-b8e87b00-58d6-11e9-92b9-c85c6bc4e195.png)
![mcr4](https://user-images.githubusercontent.com/1264210/55676501-bbe36b80-58d6-11e9-9e9c-def53b811394.png)

**Comment by tayvano** [comment]
That error message is returned from the node. The first node you connected to happened to be running geth, the second parity. Just chance that light and dark mode were different too.

**Comment by tayvano** [comment]
For the backlog: 
We should be catching all these, translating them to be helpful, and actually translating them to other languages.

**Comment by wtzb** [comment]
Thank you for opening this issue! While this is still present on our current site, the work we're doing on the new version of MyCrypto should make it obsolete. Please come check out the beta [here](https://beta.mycrypto.com/).

Thanks for helping us and letting us know of any ideas you might have, as it really helps us improve our product. I'm closing this issue here, but please know that we really appreciate any feedback you might have :)
