### ISSUE TITLE
No "Confirm Transaction" popup for transaction with data from Ledger wallet after receiving and error 

### ISSUE THREAD

**Issue by voldemarz** [MyCryptoHQ/MyCrypto#2487]
### Description of Issue
After getting an error described as described in https://github.com/MyCryptoHQ/MyCrypto/issues/2485, I no longer get Confirm Transaction popup if data field is populated.

### What exactly were you doing when you encountered this issue?
Do steps that result in error described in https://github.com/MyCryptoHQ/MyCrypto/issues/2485

After getting the error, the fields are still populated. If I try to press Send Transaction I get confirmation requests on Ledger. After confirming there is no usual "Confirm Transaction" popup in mycrypto.

If I remove contents from data field, I do get the popup. 
If I populate data field again, no popup. Have to reload the page to get it working again.

### How were you accessing your wallet?

Ledger Nano S (Firmware 1.4.2, MCU 1.6)

### Description of Your Machine

Browser: Google Chrome
Browser version: Version 73.0.3683.103 (Official Build) (64-bit)
Operating system: Windows 10 (version 1803)
Device: Reproduced on 2 different PCs
MyCrypto.com

**Comment by wtzb** [comment]
Thanks for the report! As with https://github.com/MyCryptoHQ/MyCrypto/issues/2485, it seems that this issue is resolved by updating your Ledger device, hence why I'm closing it here.

We're also working on a brand new version of MyCrypto, which you can find [here](https://beta.mycrypto.com/), which should no longer have this issue. Again, thank you so much for your feedback, it helps us a lot with improving our product!
