### ISSUE TITLE
Unremovable space symbol in front of address causes validation failure

### ISSUE THREAD

**Issue by voldemarz** [MyCryptoHQ/MyCrypto#2501]
### Description of Issue
When you paste address with "space" symbol in front, for example 
" 0x2a0c0DBEcC7E4D658f48E01e3fA353F44050c208"
it is not visible (cursor can't move in front of it) and cannot be removed. That causes address valiation to fail, resulting in red outline and inability to make a transaction.

### What exactly were you doing when you encountered this issue?
1. Access mycrypto.com web wallet
2. Paste " 0x2a0c0DBEcC7E4D658f48E01e3fA353F44050c208" into target address field
3. Observe address validation failure

### How were you accessing your wallet?
Irrelevant

### Description of Your Machine

Browser: Google Chrome
Browser version: Version 73.0.3683.103 (Official Build) (64-bit)
Operating system: Windows 10 (version 1803)
Device: Reproduced on 2 different PCs
MyCrypto.com

### Console Logs / Screenshots
![image](https://user-images.githubusercontent.com/1264210/56083513-51768200-5e26-11e9-84b5-f9b6d421b2cf.png)

**Comment by wtzb** [comment]
Thank you for opening this issue! While this is still present on our current site, the work we're doing on the new version of MyCrypto should make it obsolete. Please come check out the beta [here](https://beta.mycrypto.com/).

Thanks for helping us and letting us know of any ideas you might have, as it really helps us improve our product. I'm closing this issue here, but please know that we really appreciate any feedback you might have :)
