### ISSUE TITLE
High CPU usage and freeze system (Linux)

### ISSUE THREAD

**Issue by garywill** [MyCryptoHQ/MyCrypto#2505]
### Description of Issue
`linux-x86-64_1.6.4_MyCrypto.AppImage` encounter high CPU and freeze problem.
...

### What exactly were you doing when you encountered this issue?

1. Unlock Mnemonic Phrase clicking "choose address"
1. On "Select an Address" dialog, select TREZOR(ETC).
1. Select  "-TOKEN-" BNB
1. high CPU, system freeze for 30 sec

### How were you accessing your wallet?

Mnemonic Phrase

### Description of Your Machine

- Browser:
- Browser version:
- Operating system: Linux x64
- Device: Desktop
- MyCrypto.com vs Desktop Application?
- MyCrypto Version Number: 1.6.4

### Console Logs / Screenshots

Network log shows repeatly requests after selecting some "-TOKEN-"

**Comment by wtzb** [comment]
Thank you for opening this issue! While this is still present on our current site, the work we're doing on the new version of MyCrypto should make it obsolete. Please come check out the beta [here](https://beta.mycrypto.com/).

Thanks for helping us and letting us know of any ideas you might have or issues you might run into, as it really helps us improve our product. I'm closing this issue here, but please know that we really appreciate any feedback you might have :)
