### ISSUE TITLE
Desktop app, Contracts, Allow saving abis for custom contracts

### ISSUE THREAD

**Issue by p-s-dev** [MyCryptoHQ/MyCrypto#2531]
"Select Existing Contract" menu is read-only.

When I paste in a custom ABI, it would be awesome if it let me name it and save it at the top of the "Select Existing Contract" list.

**Comment by wtzb** [comment]
Thanks for submitting this feature request! We have since implemented this, along with a bunch of other new features, in the new beta version of MyCrypto which you can find [here](https://beta.mycrypto.com/).

Thanks for helping us and letting us know of any ideas you might have, as it really helps us improve our product. I'm closing this issue here, but please know that we really appreciate any feedback you might have :)
