### ISSUE TITLE
Basically the app begins consuming all CPU resources and freezes on a $3,500 MBP when I go to the send page using a hardware wallet

### ISSUE THREAD

**Issue by JohnAllen** [MyCryptoHQ/MyCrypto#2652]
MacOS Latest Version of MyCrypto 1.6.8.

Basically the app begins consuming all CPU resources on a $3,500 MBP when I go to the send page using a hardware wallet.  Makes it unusable unfortunately.

**Comment by CryptoQueen628** [comment]
Thanks for raising this issue. We are looking into it.

**Comment by CryptoQueen628** [comment]
@JohnAllen does the app freeze when you try to connect your hardware wallet or after?

**Comment by Mrtenz** [comment]
@JohnAllen Did you select a token in the address selection screen, right after clicking the "Connect to Ledger/Trezor"-button?

![](https://i.imgur.com/zvweuLs.png)

If so, try changing that back to the default setting ("-Token-").

**Comment by JohnAllen** [comment]
I couldn't even select a token. I was attempting to but the app was frozen.  My wallet was already attached.

**Comment by tayvano** [comment]
Hey @JohnAllen, we haven't done much to address this to be honest, but we have pushed a few updates live since we last chatted.

Have you still been encountering this issue on a regular basis? And is it always while connecting to your hardware wallet, or other times as well?

Any further information you can provide will obviously allow us to further debug / resolve...assuming this is still an ongoing issue.

Thanks for your patience and assistance here. 💖

**Comment by JohnAllen** [comment]
I haven't used the app again so not sure if your updates have fixed this. I ended up sending the tokens another way I think.  I will close this and I can open a new issue if it happens again. Thanks
