### ISSUE TITLE
Reference to localback.net in official build

### ISSUE THREAD

**Issue by SwaroopH** [MyCryptoHQ/MyCrypto#2717]
### Description of Issue

I noticed that the official MacOS build from download.mycrypto.com tries to connect to localback.net and denying access to it stalls the app. Could be related to build issue as described in #2099. I cannot seem to find any reference to that domain in the code.

EDIT: ~Using the build from Github release works fine.~ Nope, Github release seems to connect to that domain as well.

### What exactly were you doing when you encountered this issue?

1. Download MacOS build from official website.
2. Monitor traffic in firewall like Little Snitch. 

### How were you accessing your wallet?

N/a

### Description of Your Machine

- Browser: Firefox
- Browser version: 68.0.2 (64-bit)
- Operating system: OSX 10.14.6
- Device: MBP
- MyCrypto.com vs Desktop Application? Desktop
- MyCrypto Version Number: 1.7.1

### Console Logs / Screenshots

![Screenshot 2019-08-19 19 42 36](https://user-images.githubusercontent.com/62628/63272343-82c1fb80-c2b9-11e9-91b6-558e6b663362.png)

...

**Comment by mwbailey** [comment]
Hi @SwaroopH.

As @tayvano indicated, this relates to Trezor's bridge, which is a separate program (installed only by those who use Trezor devices) that starts a local web server to communicate with both a Trezor device and a browser. Non-Trezor users wouldn't have the bridge installed, but MyCrypto doesn't know this until it checks at startup.

The old version of the bridge (`trezord`, which has been obsoleted by the newer `trezord-go`) used `https://localback.net:21324`, which redirected to `https://localhost:21324`. This was probably to avoid the user being confronted with invalid certificate warnings when using https on localhost.

Newer versions of the `trezor-link` library (starting with 1.6.0) only check for the `trezord-go` bridge, which would be running on the unencrypted `http://localhost:21325`. MyCrypto, however, is currently using `trezor-link` 1.5.2, which checks for the older `trezord` as a fallback option using the now obsolete localback.net method if `trezord-go` is not found.

It shouldn't matter whether you allow or deny access to localback.net. The connection will fail either way, but MyCrypto should continue to run as expected. If connections to localback.net are denied, it will fail immediately since it can't connect to the host. If allowed, the connection will eventually time out since there is no longer any server running at `https://localback.net:21324`. Regardless, the failed connection should not have any noticeable effect on MyCrypto.

I suspect the reason MyCrypto stalled for you has to do with the delay caused by Little Snitch's popup asking to allow or deny access (if you don't have a preexisting rule for a domain). In my testing, if you respond within ~15 seconds (doesn't matter whether to allow or deny), MyCrypto runs fine. If you wait longer than that, MyCrypto will stall.

I think this has to do with the way Little Snitch captures and holds packets at the application layer. It doesn't appear to send any packets to the network interface until the initial localback.net popup has been closed, even if other domains (mycryptoapi.com, infura.io, etherscan.io, etc. already have rules allowing access). If you don't respond in time, none of the connections that MyCrypto attempts on startup ever hit the network.

Can you check to see if the MyCrypto app runs properly if there's a permanent Little Snitch rule denying access to localback.net or if you quickly hit 'Deny' on the popup? Let me know if there's still a problem, and I'll take another look.

**Comment by SwaroopH** [comment]
@mwbailey thanks for looking into this, it makes sense to me now. Never had a Trezor but I guess one of the older eth clients may have installed it.

I was able to get MyCrypto to work by adding the exception.
