### ISSUE TITLE
Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by Megachance** [MyCryptoHQ/MyCrypto#2728]
Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### Description of Issue

...

### What exactly were you doing when you encountered this issue?

...Give us some steps to reproduce...

### How were you accessing your wallet?

...Ledger, Trezor, MetaMask, Private Key, Keystore File, Parity Signer, Mnemonic Phrase?...

### Description of Your Machine

- Browser:
- Browser version:
- Operating system:
- Device:
- MyCrypto.com vs Desktop Application?
- MyCrypto Version Number:

### Console Logs / Screenshots

...

**Comment by Megachance** [comment]
Ledger Zugang

**Comment by wtzb** [comment]
Thank you for opening this issue! While this is still present on our current site, the work we're doing on the new version of MyCrypto should make it obsolete. Please come check out the beta [here](https://beta.mycrypto.com/).

In the meanwhile. this issue can be solved by clearing your browser cache for mycrypto.com.

Thanks for helping us and letting us know of any ideas you might have or issues you might run into, as it really helps us improve our product. I'm closing this issue here, but please know that we really appreciate any feedback you might have :)
