### ISSUE TITLE
Make tx-status page great again

### ISSUE THREAD

**Issue by VinceBCD** [MyCryptoHQ/MyCrypto#3342]
### Description of Issue

The https://www.mycrypto.com/tx-status page seems to be missing in the beta version. The purpose of this issue is therefore to put it back in place to avoid a loss of functionality in the new version and take advantage of it to improve it, especially in terms of UX.

Notably, it would be interesting:
- to make it possible to pass parameters to this page (blockchain used, tx address) - triggering automatically the "Check Tx status" just as the interact-with-contracts page
- ideally, and especially when the tx is passed as a parameter, the end user would not have to scroll to see the tx information. The idea is that he accesses the desired information (e.g. the fact that the transaction is "SUCCESSFUL") as simply and directly as possible.

Of course, the page would remain accessible without wallet as the "interact with contracts" page for read-only functions.

### What exactly were you doing when you encountered this issue?

Just trying to access the https://www.mycrypto.com/tx-status page on the beta version

### How were you accessing your wallet?

no wallet needed

### Description of Your Machine

Browser: chrome
Browser version: 80.0.3987.149 (Official Build) (64-bit)
Operating system: Windows 10
Device: Microsoft Surface Pro
MyCrypto.com vs Desktop Application? MyCrypto.com
MyCrypto Version Number: beta

**Comment by wtzb** [comment]
Hi there @VinceBCD, thank you so much for bringing attention to this! I wanted to let you know that this has since been added to our internal project management system, so we have a better overview at the tasks at hand. For this reason, I will be closing this issue here, but please do know that we're really thankful for your feedback, and that it absolutely helps us with making MyCrypto the best it can be.

If you do happen to have any additional feedback or questions, then please don't hesitate to let us know! You can do it through here, or contact us directly via our [knowledge base](https://support.mycrypto.com/contact-us). Thank you so much!
