### ISSUE TITLE
*BSD installation/compilation?

### ISSUE THREAD

**Issue by dchmelik** [MyCryptoHQ/MyCrypto#3407]
Can't install (or compile?) on FreeBSD 13-CURRENT.

### Console Logs / Screenshots

u@cosmos:~/MyCrypto-1.7.11$ rm -rf node_modules/ && yarn 
yarn install v1.22.4
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info 7zip-bin-linux@1.3.1: The platform "freebsd" is incompatible with this module.
[...]
info fsevents@1.1.3: The platform "freebsd" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
error upath@1.0.4: The engine "node" is incompatible with this module. Expected version ">=4 <=9". Got "14.5.0"
error Found incompatible module.

### Description of Your Machine

- Operating system: FreeBSD 13-CURRENT
- Device: x86_64 desktop workstation
- MyCrypto Version Number: 1.7.11

**Comment by mwbailey** [comment]
Hi @dchmelik,

You're using Node 14, instead of the required Node 8: https://github.com/MyCryptoHQ/MyCrypto/tree/1.7.11#development--build-requirements

[nvm](https://github.com/nvm-sh/nvm) is typically the best way to manage multiple versions of Node, although it looks like there may be some issues installing on FreeBSD: https://github.com/nvm-sh/nvm#important-notes

**Comment by Legogris** [comment]
@mwbailey Are you aware if there is any plan to migrate to 12, the latest LTS, or at the very least 10? node v8 is end-of-life and does not receive updates since 2019-12-31.

**Comment by Mrtenz** [comment]
@Legogris We are working on updating the legacy branch to Node v10. The beta app (master branch) is already running on Node v12, but there's no desktop application for it yet.

**Comment by Mrtenz** [comment]
#3363
