### ISSUE TITLE
Refresh Balance Button

### ISSUE THREAD

**Issue by dternyak** [MyCryptoHQ/MyCrypto#446]
User request - allow updating of balances without refreshing / re-decrypting wallet via a button next to the display ether balance.

**Comment by dternyak** [comment]
Alternatively, consider integrating with [Etherscan's Websocket API](https://etherscan.io/apis#websocket) that should even further improve UX.

**Comment by timeffect** [comment]
I'm thinking of taking a look at this, but where in the app can the user view their balances?

The only view I've found so far is the `/send-transaction` route. Are there other views in the app to check balances or somewhere in the pipeline? 

If so, I suppose we should generalize this into it's own react component.

**Comment by dternyak** [comment]
@timeffect Thanks for your interest Tim!

Currently, the send view is the only view where users are able to view their balances.

Having a separate React component is definitely the way to go 👍

**Comment by wbobeirne** [comment]
The only other spot is the mnemonic modal, but I think that doesn't really need a refresh.

**Comment by dternyak** [comment]
Right - though to confirm you mean confirmation modal, not mnemonic modal right @wbobeirne?

**Comment by timeffect** [comment]
Good to keep in mind.

**Comment by tayvano** [comment]
If it doesn't already, can the balance displayed in sidebar update when you press the "Generate TX" button. Right now on v3 it pulls balance in order to ensure the user has enough balance send but doesn't update the display in the sidebar. 

If users are sending back-to-back and encountering errors, updating the display on generate would help them debug. 

If WebSockets aren't ready yet, we could do a balance pull ~45 seconds after the user broadcasts a transaction without creating too much additional load on the backend. Mildly hacky but would get the job done in most cases.
