### ISSUE TITLE
Refresh Nonce Button

### ISSUE THREAD

**Issue by dternyak** [MyCryptoHQ/MyCrypto#632]
From https://github.com/MyEtherWallet/MyEtherWallet/issues/30

Allows users to get up-to-date nonce if they believe the most recently loaded nonce while building a transaction may be out of date.

**Comment by tayvano** [comment]
If anyone has any insights on how to keep user connected to same node behind the load balancer, I'm all ears. This may also be resolved when we make some improvements to the backend / caching.

This is happening a lot lately due to (1) full tx pools (2) hitting different nodes which may not have received the latest tx yet (3) being 100% on parity ATM which handles grabbing transaction count (the nonce) a bit differently than geth.

@skubakdj can probably provide more insights, but ideally the user would never have to refresh the nonce so there wouldn't have to be a button. 😊

**Comment by dternyak** [comment]
I don't know of a way to ensure that a request is routed to a specific node behind the load-balancer, but that's certainly an interesting concept.

Even in the case where the node returns the "correct" nonce after the user decrypts their wallet, they may have sent a tx from another wallet using the same private key. Unless we have a websocket that will push the updated nonce, or we poll, the user wouldn't be able to have their nonce automatically updated in this case (without taking action to refresh themselves).
