### ISSUE TITLE
Set Gas Price to default if user navigates away with invalid state

### ISSUE THREAD

**Issue by dternyak** [MyCryptoHQ/MyCrypto#888]
Users will encounter an exception in the following scenario:

1. Set gas price to empty input
2. Navigate away
3. Unlock wallet
4. Notice exception screen

- [ ] Dispatch action setting gas price to default on component unmount.

**Comment by wbobeirne** [comment]
I think the issue here is that all of our types are set up to ensure that gas price is never undefined / null, but in this case it can be. We should probably just never let it be those values, either opting for zero instead, or just not firing the set gas price action if a valid returns a non-positive value.
