### ISSUE TITLE
MEW-01-008 Web: Transaction History URL allows javascript URIs

### ISSUE THREAD

**Issue by dternyak** [MyCryptoHQ/MyCrypto#948]

**Comment by wbobeirne** [comment]
https://github.com/Microsoft/TypeScript/issues/6579 would be a huge boon to this, if we could have a `URL` type that enforced HTTPS at the typescript level to fail builds.

As it stands though, I feel kind of indifferent to this one. If this config ever goes dynamic (e.g. retrieved from an API request) then I'd feel strongly about enforcing this, but with the current code and deploy process, this would have the same likelihood of getting in any other malicious code in the bundle. Actually, even less likely, because a node module could put in malicious code, but this would have to come from our own source. Even Cure53 kind of agrees as much:

> The exploitation of this vulnerability is currently impossible because none of these twoproperties can be employed for a custom node.
>
> ... Although the vulnerability cannot be reached by an attacker at present, it can pose a risk in the future when additional features are added to the platform, especially in connection with allowing custom explorer URLs.

I'd say until we get to a point where we have a feature that allows for custom `<a href="...">` tags, we punt on this. And if that time comes, we should just have a `<ValidatedAnchor href="...">` component that makes sure it's HTTPS.

**Comment by wbobeirne** [comment]
After some internal discussion, we've come to the conclusion that there are no preventative measures to take for this potential security issue at the moment. If the code for networks changes to where these values are dynamic (Whether it be from user input, URL queries, API requests, whatever) we'll want to revisit this to ensure that the links are not malicious.
