### ISSUE TITLE
Prefilled transaction is broken

### ISSUE THREAD

**Issue by wbobeirne** [MyCryptoHQ/MyCrypto#968]
Since the change from `/send-transaction` to `/account/send`, we lose the query parameters upon navigation. We'll need to find a way to carry over the data from the query.

**Comment by wbobeirne** [comment]
This will also be difficult to maintain with the large number of `reset` actions we've sprinkled in our components, that will likely lose this state. My proposal for how we do this is:

1. Add something to redux that tracks query parameters on initial load.
2. Add an action to transaction, something like `setFieldsFromQuery`.
3. Fire this action when we load the send transaction fields.
4. In the saga, make sure this action only actually sets the field(s) once. Subsequent views of the transaction fields shouldn't force the query parameters in again.

cc @HenryNguyen5, if you have ideas on implementation I think you've probably got an idea for how to do this cleanest.

**Comment by HenryNguyen5** [comment]
Yeah this makes sense.
1. Get rid of the `Query` component
2. On load / URL change we can have a property in redux store that loads in parsed query payload (Going to need validation on it though, but the existing validators can be used pretty easily).
3. Have an action for loading the query state into transaction state and validate it (again, can re-use actions like `setCurrentValue` `setCurrentTo` that will automatically validate the data being passed in

On a side note: It would be nice to centralise reset hooks for the sagas in one place so its easy to keep track of whats going to reset slices of state.

**Comment by aitrean** [comment]
So, I definitely tried this solution. However, I don't believe it would be the best solution for four reasons. 

1. We need to maintain the queries in the router, otherwise the query will disappear from the URL, which will make the user think we ignored the query.

2. If we're going to pass the query data to account/send, then it becomes redundant to keep a Redux state for the query data. The query data still loads as the default 'to' and 'value' items under the transaction tree. There are no sagas that explicitly use a "query" state in the store. And, on the UI side, the behaviour seems to function exactly as intended. 

3. There are reset hooks which will reset the prefilled transactions. But these resets only trigger when we're clearing the transaction fields anyway. For example, subtab navigation would clear a manually-entered transaction, so in my mind, it makes sense that it would also clear pre-filled transaction fields.

4. Without the overhead from managing a special query property, the solution for this issue really only boils down to a few lines of code. Of course, I still like the idea of replacing the Query HOC with a utility function to set, and load, the pre-filled state. But that would be better addressed as a separate issue.

Any different takes on this?

**Comment by wbobeirne** [comment]
I think the simplest solution is usually the best, so that's fine by me. I'm also in favor of removing the Query component for query util functions.

My only concern is the maintainability. Currently we have no testing around the query params in the codebase, and having them be ad-hoc util calls won't make that any easier to test whether or not they're working. But I'm worried about overzealous resetting or other saga side effects blowing out the prefilled state, and not having that be caught by tests.

I think I'm over-engineering though, what's most important is that this functionality is restored pre-launch, so do whichever works best!
